modLoader = "javafml"
loaderVersion = "[4,)"
license = "Custom"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"

[[mixins]]
config = "earthernware-neoforge.mixins.json"

[[mods]]
modId = "earthernware"
version = "${version}"
displayName = "[Let's Do] Earthernware"
authors = "satisfy"
description = '''
A small pottery mod focused on clay, kilns and decorative bricks. Discover new clay types and shape them into bricks, vases and flower pots.'''
logoFile = "pack.png"

[[dependencies.earthernware]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.earthernware]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.earthernware]]
modId = "architectury"
type = "required"
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"